#!/usr/bin/php
<?php

require __DIR__.'/src/vendor/Symfony/Foundation/UniversalClassLoader.php';

$loader = new Symfony\Foundation\UniversalClassLoader();
$loader->registerNamespaces(array(
  'ContainerKit' =>  __DIR__.'/src',
  'Symfony' => __DIR__.'/src/vendor',
));

$loader->registerPrefixes(array(
  'Console_' => __DIR__.'/src/vendor',
));

$loader->register();

$controller = new ContainerKit\Core\Controller();
$controller->loadConfig(__DIR__.'/config.yml');

$application = new ContainerKit\Console\Application($controller);
$application->run();