roots:
  config: /var/lib/lxc
  cgroup: /cgroup
  storage: /var/containers
executables:
  lxc-start: /usr/bin/lxc-start
  lxc-stop: /usr/bin/lxc-stop
  lxc-info: /usr/bin/lxc-info
  lxc-console: /usr/bin/lxc-console
  ip: /sbin/ip
  cp: /bin/cp
network:
  range: 192.168.2.2-192.168.2.254
  gateway: 192.168.2.1
  netmask: 255.255.255.0
  resolv.conf: |
               search example.com
               nameserver 8.8.8.8
  hostname: %name%.example.com
general:
  threads: 8
  stop_timeout: 120
  start_timeout: 60
  default_template: debian-base